"""Add assigned_to_department to tasks

Revision ID: 20c9e6a95685
Revises: bd8602f17639
Create Date: 2024-06-20 00:46:47.747775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c9e6a95685'
down_revision = 'bd8602f17639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_department', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['assigned_to_department'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_department')

    # ### end Alembic commands ###
