"""Add department_id to Task

Revision ID: 211c179370be
Revises: 8191df8329cf
Create Date: 2024-06-20 01:14:08.217280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211c179370be'
down_revision = '8191df8329cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('issued_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('issued_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
