"""Add department_id to Task

Revision ID: 97234d7c426f
Revises: 20c9e6a95685
Create Date: 2024-06-20 00:57:53.875945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97234d7c426f'
down_revision = '20c9e6a95685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.alter_column('issued_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('task_assigned_to_department_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.drop_column('assigned_to_department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_department', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_assigned_to_department_fkey', 'department', ['assigned_to_department'], ['id'])
        batch_op.alter_column('issued_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
