"""Add bio column to User table

Revision ID: 831516bdd57d
Revises: 858e6eb7eb71
Create Date: 2024-04-24 17:10:50.975889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831516bdd57d'
down_revision = '858e6eb7eb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('passport_data', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('responsibilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='Employee'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('responsibilities')
        batch_op.drop_column('position')
        batch_op.drop_column('department')
        batch_op.drop_column('passport_data')
        batch_op.drop_column('bio')
        batch_op.drop_column('role')

    op.create_table('user_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=255), nullable=True),
    sa.Column('passport_data', sa.VARCHAR(length=255), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), nullable=True),
    sa.Column('responsibilities', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
