"""Add passport_data field to UserProfile model

Revision ID: 858e6eb7eb71
Revises: a349ff88da4e
Create Date: 2024-04-24 14:46:02.575366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858e6eb7eb71'
down_revision = 'a349ff88da4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_data', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('responsibilities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('responsibilities')
        batch_op.drop_column('position')
        batch_op.drop_column('department')
        batch_op.drop_column('passport_data')

    # ### end Alembic commands ###
