"""Добавлен столбец department_id в таблицу User

Revision ID: f07b7fed736b
Revises: 23d9e0f0ad30
Create Date: 2024-05-01 23:55:53.186263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07b7fed736b'
down_revision = '23d9e0f0ad30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_department', 'department', ['department_id'], ['id'])
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='Employee'))
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_user_department', type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
